ALTER TABLE ACTIVIDAD DROP FOREIGN KEY FK_ACTIVIDAD_ONGS_ID_ONG
ALTER TABLE ESTADOACTIVIDAD DROP FOREIGN KEY FK_ESTADOACTIVIDAD_ID_ACTIVIDAD
ALTER TABLE ESTADOACTIVIDAD DROP FOREIGN KEY FK_ESTADOACTIVIDAD_DNI
ALTER TABLE INFORME DROP FOREIGN KEY FK_INFORME_PDI_DNI
ALTER TABLE INFORME DROP FOREIGN KEY FK_INFORME_ACT_ID_ACTIVIDAD
ALTER TABLE INFORME DROP FOREIGN KEY FK_INFORME_ALUMNO_DNI
ALTER TABLE USUARIO_INFORME DROP FOREIGN KEY FK_USUARIO_INFORME_Alumno_DNI
ALTER TABLE USUARIO_INFORME DROP FOREIGN KEY FK_USUARIO_INFORME_Pdi_DNI
ALTER TABLE USUARIO_INFORME DROP FOREIGN KEY FK_USUARIO_INFORME_ID_INFORME
ALTER TABLE ONG_ACTIVIDAD DROP FOREIGN KEY FK_ONG_ACTIVIDAD_ONG_ACT_ID_ACTIVIDAD
ALTER TABLE ONG_ACTIVIDAD DROP FOREIGN KEY FK_ONG_ACTIVIDAD_ONG_ID_ONG
DROP TABLE ACTIVIDAD
DROP TABLE USUARIO
DROP TABLE ESTADOACTIVIDAD
DROP TABLE INFORME
DROP TABLE ONG
DROP TABLE USUARIO_INFORME
DROP TABLE ONG_ACTIVIDAD
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
