--<ScriptOptions statementTerminator=";"/>

CREATE TABLE USUARIO (
	DNI INT NOT NULL,
	DTYPE VARCHAR(31),
	APELLIDOS VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	F_NACMIMIENTO DATE,
	NOMBRE VARCHAR(255) NOT NULL,
	PASSWORD VARCHAR(8) NOT NULL,
	GRADO_FACULTAD VARCHAR(255),
	DEPARTAMENTO VARCHAR(255),
	DESPACHO VARCHAR(255),
	TIPO_SERVICIO VARCHAR(255),
	PRIMARY KEY (DNI)
);

CREATE TABLE SEQUENCE (
	SEQ_NAME VARCHAR(50) NOT NULL,
	SEQ_COUNT DECIMAL(10 , 0),
	PRIMARY KEY (SEQ_NAME)
);

CREATE TABLE ONG_ACTIVIDAD (
	ONG_ID_ONG INT NOT NULL,
	ONG_ACT_ID_ACTIVIDAD BIGINT NOT NULL,
	PRIMARY KEY (ONG_ID_ONG,ONG_ACT_ID_ACTIVIDAD)
);

CREATE TABLE INFORME (
	ID_INFORME BIGINT NOT NULL,
	DTYPE VARCHAR(31),
	DESCRIPCION VARCHAR(255) NOT NULL,
	EVALUACION_ID_INFORME BIGINT,
	INF_PDI_DNI INT,
	CALIFICACION FLOAT,
	PRIMARY KEY (ID_INFORME)
);

CREATE TABLE USUARIO_SOLICITUD_ACTIVIDAD (
	Usuario_DNI INT NOT NULL,
	ID_USUARIO_DNI INT NOT NULL,
	ID_ACTIVIDAD_ID_ACTIVIDAD BIGINT NOT NULL,
	PRIMARY KEY (Usuario_DNI,ID_USUARIO_DNI,ID_ACTIVIDAD_ID_ACTIVIDAD)
);

CREATE TABLE USUARIO_INFORME (
	Alumno_DNI INT NOT NULL,
	INF_AL_ID_INFORME BIGINT NOT NULL,
	Pdi_DNI INT NOT NULL,
	PDI_INFORME_ID_INFORME BIGINT NOT NULL,
	PRIMARY KEY (Alumno_DNI,INF_AL_ID_INFORME,Pdi_DNI,PDI_INFORME_ID_INFORME)
);

CREATE TABLE SOLICITUD_ACTIVIDAD (
	ESTADO VARCHAR(255) NOT NULL,
	ID_ACTIVIDAD_ID_ACTIVIDAD BIGINT NOT NULL,
	ID_USUARIO_DNI INT NOT NULL,
	PRIMARY KEY (ID_ACTIVIDAD_ID_ACTIVIDAD,ID_USUARIO_DNI)
);

CREATE TABLE ACTIVIDAD_SOLICITUD_ACTIVIDAD (
	Actividad_ID_ACTIVIDAD BIGINT NOT NULL,
	ID_USUARIO_DNI INT NOT NULL,
	ID_ACTIVIDAD_ID_ACTIVIDAD BIGINT NOT NULL,
	PRIMARY KEY (Actividad_ID_ACTIVIDAD,ID_USUARIO_DNI,ID_ACTIVIDAD_ID_ACTIVIDAD)
);

CREATE TABLE ONG (
	ID_ONG INT NOT NULL,
	AMBITO VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	NOMBRE VARCHAR(255) NOT NULL,
	TELEFONO INT NOT NULL,
	PRIMARY KEY (ID_ONG)
);

CREATE TABLE ACTIVIDAD (
	ID_ACTIVIDAD BIGINT NOT NULL,
	AMBITO VARCHAR(255) NOT NULL,
	DESCRIPCION VARCHAR(255) NOT NULL,
	ESTADO VARCHAR(255),
	F_FIN DATE NOT NULL,
	F_INICIO DATE NOT NULL,
	ACT_ONG_ID_ONG INT,
	PRIMARY KEY (ID_ACTIVIDAD)
);

CREATE TABLE ACTIVIDAD_INFORME (
	Actividad_ID_ACTIVIDAD BIGINT NOT NULL,
	INF_AL_ID_INFORME BIGINT NOT NULL,
	PRIMARY KEY (Actividad_ID_ACTIVIDAD,INF_AL_ID_INFORME)
);

CREATE INDEX FK_ACTIVIDAD_INFORME_INF_AL_ID_INFORME ON ACTIVIDAD_INFORME (INF_AL_ID_INFORME ASC);

CREATE INDEX FK_USUARIO_INFORME_Pdi_DNI ON USUARIO_INFORME (Pdi_DNI ASC);

CREATE INDEX USUARIOSOLICITUDACTIVIDADID_ACTIVIDAD_ID_ACTIVIDAD ON USUARIO_SOLICITUD_ACTIVIDAD (ID_ACTIVIDAD_ID_ACTIVIDAD ASC);

CREATE INDEX FK_ONG_ACTIVIDAD_ONG_ACT_ID_ACTIVIDAD ON ONG_ACTIVIDAD (ONG_ACT_ID_ACTIVIDAD ASC);

CREATE INDEX FK_INFORME_INF_PDI_DNI ON INFORME (INF_PDI_DNI ASC);

CREATE INDEX FK_ACTIVIDAD_ACT_ONG_ID_ONG ON ACTIVIDAD (ACT_ONG_ID_ONG ASC);

CREATE INDEX FK_SOLICITUD_ACTIVIDAD_ID_USUARIO_DNI ON SOLICITUD_ACTIVIDAD (ID_USUARIO_DNI ASC);

CREATE INDEX ACTIVIDADSOLICITUDACTIVIDADIDACTIVIDADID_ACTIVIDAD ON ACTIVIDAD_SOLICITUD_ACTIVIDAD (ID_ACTIVIDAD_ID_ACTIVIDAD ASC);

CREATE INDEX ACTIVIDADSOLICITUDACTIVIDADIDACTIVIDADID_ACTIVIDAD ON ACTIVIDAD_SOLICITUD_ACTIVIDAD (ID_USUARIO_DNI ASC);

CREATE INDEX FK_INFORME_EVALUACION_ID_INFORME ON INFORME (EVALUACION_ID_INFORME ASC);

CREATE INDEX FK_USUARIO_INFORME_PDI_INFORME_ID_INFORME ON USUARIO_INFORME (PDI_INFORME_ID_INFORME ASC);

CREATE INDEX FK_USUARIO_INFORME_INF_AL_ID_INFORME ON USUARIO_INFORME (INF_AL_ID_INFORME ASC);

CREATE INDEX USUARIOSOLICITUDACTIVIDADID_ACTIVIDAD_ID_ACTIVIDAD ON USUARIO_SOLICITUD_ACTIVIDAD (ID_USUARIO_DNI ASC);

ALTER TABLE SOLICITUD_ACTIVIDAD ADD PRIMARY KEY (ID_ACTIVIDAD_ID_ACTIVIDAD, ID_USUARIO_DNI);

ALTER TABLE ACTIVIDAD_SOLICITUD_ACTIVIDAD ADD PRIMARY KEY (Actividad_ID_ACTIVIDAD, ID_USUARIO_DNI, ID_ACTIVIDAD_ID_ACTIVIDAD);

ALTER TABLE SOLICITUD_ACTIVIDAD ADD UNIQUE (ID_USUARIO_DNI);

ALTER TABLE ACTIVIDAD ADD PRIMARY KEY (ID_ACTIVIDAD);

ALTER TABLE SOLICITUD_ACTIVIDAD ADD CONSTRAINT FK_SOLICITUD_ACTIVIDAD_ID_USUARIO_DNI FOREIGN KEY (ID_USUARIO_DNI)
	REFERENCES USUARIO (DNI)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE ACTIVIDAD_SOLICITUD_ACTIVIDAD ADD CONSTRAINT ACTIVIDADSOLICITUD_ACTIVIDADActividad_ID_ACTIVIDAD FOREIGN KEY (Actividad_ID_ACTIVIDAD)
	REFERENCES ACTIVIDAD (ID_ACTIVIDAD)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE SOLICITUD_ACTIVIDAD ADD CONSTRAINT FK_SOLICITUD_ACTIVIDAD_ID_ACTIVIDAD_ID_ACTIVIDAD FOREIGN KEY (ID_ACTIVIDAD_ID_ACTIVIDAD)
	REFERENCES ACTIVIDAD (ID_ACTIVIDAD)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE ACTIVIDAD_SOLICITUD_ACTIVIDAD ADD CONSTRAINT ACTIVIDADSOLICITUDACTIVIDADIDACTIVIDADID_ACTIVIDAD FOREIGN KEY (ID_ACTIVIDAD_ID_ACTIVIDAD, ID_USUARIO_DNI)
	REFERENCES SOLICITUD_ACTIVIDAD (ID_ACTIVIDAD_ID_ACTIVIDAD, ID_USUARIO_DNI)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

